M48
; DRILL file {KiCad 7.0.5-0} date 2024 February 27, Tuesday 14:02:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-27T14:02:59-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X130.81Y-58.547
X130.81Y-111.76
X185.42Y-58.547
X185.42Y-111.76
T2
X160.274Y-92.179
T0
M30
